registry:
  # Docker registry url
  url: https://registry.duckdns.org:5000/v2
  # Docker registry fqdn
  name: //registry.duckdns.org:5000
  # To allow image delete, should be false
  readonly: false
  auth:
    # Disable authentication
    enabled: true
